<a href="https://colab.research.google.com/github/atfan7/Probability-and-Statistics-Projects/blob/main/Chisquared_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from scipy.stats import chi2_contingency

'''
H0: Marital status and alcohol consumption are not associated.
Ha: Marital status and alcohol consumption are associated. '''

observed = [[67,213,74], [411,633,129], [85,51,7], [27,60,15]]
test_statistic, p_value, dof, expected_values = chi2_contingency(observed)

print("Test statistic:", test_statistic)
print("p-value:", p_value)

alpha = 0.05

if(p_value < alpha):
  print("Reject H0 (Null Hypothesis),i.e. Marital status and alcohol consumption are associated.")
else:
  print("Fail to Reject H0 (Null Hypothesis),i.e. Marital status and alcohol consumption are not associated.")

Test statistic: 94.26880078578765
p-value: 3.925170647869838e-18
Reject H0 (Null Hypothesis),i.e. Marital status and alcohol consumption are associated.


In [6]:
import numpy as np
from scipy.stats import chi2_contingency

# Create a 2D NumPy array with the observed data
observed = np.array([[33,218],
[25,389],
[20, 393],
[17, 178]])

# Perform a chi-squared test for independence
chi2, p, df, exp_freq = chi2_contingency(observed)

# Define the significance level
alpha = 0.1

# Print the chi-squared statistic and p-value
print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"df: {df}")
print(f"expected frequency: {exp_freq}")

# Compare the p-value to the significance level
if p < alpha:
  print("Reject the null hypothesis. Conclusion: education level and diabetic state are associated")
else:
  print("Fail to reject the null hypothesis. Conclusion: education level and diabetic state are not associated")

Chi-squared statistic: 17.51186847271713
P-value: 0.000554511571355531
df: 3
expected frequency: [[ 18.73134328 232.26865672]
 [ 30.89552239 383.10447761]
 [ 30.82089552 382.17910448]
 [ 14.55223881 180.44776119]]
Reject the null hypothesis. Conclusion: education level and diabetic state are associated


In [8]:
from scipy.stats import chi2_contingency
observed = [[77,149,78],
[23,56,36],
[8,24,29],
[6,15,8]]

test_statistic, p_value, dof, expected_values = chi2_contingency(observed)

print("Test statistic:", test_statistic)
print("p-value:", p_value)

alpha = 0.05

if(p_value < alpha):
  print("Reject H0 (Null Hypothesis,association exists between religiosity and education)")
else:
  print("Fail to Reject H0 (Null Hypothesis),no concrete evidence")

Test statistic: 13.322313008960627
p-value: 0.038193742691133806
Reject H0 (Null Hypothesis)


In [10]:
import numpy as np
from scipy.stats import chi2_contingency

# Create a 2D NumPy array with the observed data
observed = np.array([[335,348, 318],
[35, 23, 50]])

# Perform a chi-squared test for independence
chi2, p, df, exp_freq = chi2_contingency(observed)
p = round(p,3)

# Define the significance level
alpha = 0.01

# Print the chi-squared statistic and p-value
print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"df: {df}")
print(f"expected frequency: {exp_freq}")

# Compare the p-value to the significance level
if p < alpha:
  print(f"Reject the null hypothesis. p_value={p}, response and regions are associated")
else:
  print(f"Fail to reject the null hypothesis. p_value={p}, response and regions are not associated")


Chi-squared statistic: 11.519544916042339
P-value: 0.003
df: 2
expected frequency: [[333.96753832 334.87015329 332.16230839]
 [ 36.03246168  36.12984671  35.83769161]]
Reject the null hypothesis. p_value=0.003, response and regions are associated


In [11]:
#H0: Age and internet usage are independent.
#Ha: Age and internet usage are associated.

alpha = 0.01

observed = [
    [6, 38, 31],
    [14, 31, 4],
    [50, 50, 5]
]

chi_stat, p_value, df , exp_freq = chi2_contingency(observed)
print(chi_stat)
print(p_value)
print(df)
print(exp_freq)

if p_value < alpha:
  print("Reject H0")
  print("Age and internet usage are associated.")
else:
  print("Fail to reject H0")
  print("Age and internet usage are independent.")

60.74604310295546
2.0217185191724964e-12
4
[[22.92576419 38.97379913 13.10043668]
 [14.97816594 25.4628821   8.55895197]
 [32.09606987 54.56331878 18.34061135]]
Reject H0
Age and internet usage are associated.


In [13]:
import numpy as np
from scipy.stats import chi2_contingency

# Create a 2D NumPy array with the observed data
observed = np.array([[75, 106, 46],
[106, 161, 61],
[98, 183, 52],
[48, 102, 14]
])

# Perform a chi-squared test for independence
chi2, p, df, exp_freq = chi2_contingency(observed)
p = round(p,3)

# Define the significance level
alpha = 0.05

# Print the chi-squared statistic and p-value
print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"df: {df}")
print(f"expected frequency: {exp_freq}")

# Compare the p-value to the significance level
if p < alpha:
  print(f"Reject the null hypothesis. p_value={p}, type of residence is related to income level")
else:
  print(f"Fail to reject the null hypothesis. p_value={p}, type of residence is not related to income level")


Chi-squared statistic: 15.727554171801787
P-value: 0.015
df: 6
expected frequency: [[ 70.55988593 119.11026616  37.32984791]
 [101.95437262 172.10646388  53.9391635 ]
 [103.50855513 174.73003802  54.76140684]
 [ 50.97718631  86.05323194  26.96958175]]
Reject the null hypothesis. p_value=0.015, type of residence is related to income level


In [14]:
import scipy.stats as stats

# Observed frequencies from your survey
observed = [73, 38, 18]

# Expected frequencies based on the original survey
total_surveyed = sum(observed)
expected = [0.60 * total_surveyed, 0.28 * total_surveyed, 0.12 * total_surveyed]

# Perform the chi-squared test
chi_squared, p_value = stats.chisquare(f_obs=observed, f_exp=expected)

# Set the significance level
alpha = 0.05

# Determine the critical chi-squared value (2 degrees of freedom)
critical_chi_squared = stats.chi2.ppf(1 - alpha, df=2)

# Print the results
print(f"Chi-Squared Statistic: {chi_squared}")
print(f"P-Value: {p_value}")
print(f"Critical Chi-Squared Value: {critical_chi_squared}")

# Make a decision
if chi_squared > critical_chi_squared:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")


Chi-Squared Statistic: 0.7582133628645247
P-Value: 0.6844725882551137
Critical Chi-Squared Value: 5.991464547107979
Fail to reject the null hypothesis


In [17]:
#H0: Coin is fair.
#Ha: Coin is biased.

alpha = 0.05

chi_stat , p_value = stats.chisquare(
    [48, 52],
    [50, 50]
)

print(chi_stat)
print(p_value)

if p_value < alpha:
  print("Reject H0")
  print("Coin is biased.")
else:
  print("Fail to reject H0")
  print("Coin is fair.")

0.16
0.6891565167793516
Fail to reject H0
Coin is fair.


In [23]:
# Ho : Distribution of preferences matches your expectations. (Null Hypothesis)
# Ha : Distribution of preferences does not matches your expectations. (Alternate Hypothesis)
import scipy.stats as stats
from scipy.stats import chi2_contingency

expected = [60, 80, 60]
observed = [70, 80, 50]
alpha = 0.05

chi_stat, p_value = stats.chisquare(observed, expected)

if p_value < alpha:
    print("Reject null hypo, distribution of preferences does not matches your expectations")
else:
    print("Can't reject null Hypo , distribution of preferences matches your expectations")

print(f"P Value : {p_value}")
print(f"Chi Statistic : {chi_stat}")


Can't reject null Hypo , distribution of preferences matches your expectations
P Value : 0.1888756028375618
Chi Statistic : 3.3333333333333335
